# Generated by Django 4.1.4 on 2022-12-22 10:23

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Gallery.get_file_name)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='about',
            name='desc_body',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='events',
            name='desc',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
